### ISSUE TITLE
Branch protection rules

### ISSUE THREAD

**Issue by brplcc** [Alpha-Authority/Szeebe#11]
Make branch protection rules for main.

**Comment by Scrippy** [comment]
New rules need review, tho should be fine for now.

**Comment by Scrippy** [comment]
Re-reviewing.

**Comment by Scrippy** [comment]
Important Resources for Future Use.

https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git
https://github.com/cli/cli#installation

**Comment by Scrippy** [comment]
Other Important Resources Related to Archiving Older Branches.

https://dev.to/clsource/archiving-git-branches-3k70

 git checkout old_main-testing 
 git tag archive/branch-old_main-testing old_main-testing 
 git push origin --tags

https://stackoverflow.com/questions/5480258/how-can-i-delete-a-remote-tag

git push --delete origin archive/old_main-testing

**Comment by Scrippy** [comment]
Ruleset setup for all branches. Old branches archived and protected.
