### ISSUE TITLE
.sh file Creation Needed for Reset command

### ISSUE THREAD

**Issue by Scrippy** [Alpha-Authority/Szeebe#12]
Literally: pm2 restart index

and we're done 💀 

Replacing the old function which just relogs the bot in with an actual restart command w/e

**Comment by brplcc** [comment]
On it.

**Comment by brplcc** [comment]
Took a different approach of just running the commands straight from Node.js.
11bd349700d2f9c168a2b6d04aa41fda225e873c

**Comment by Scrippy** [comment]
Fixed
